version: '3.4'

services:
  gateway:
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    container_name: ocp10_gateway
    ports:
      - "5000:5000"
    depends_on:
      - patientservice
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "5000"

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    container_name: ocp10_frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile

  patientservice:
    image: ${DOCKER_REGISTRY-}patientservice
    container_name: ocp10_patientservice
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=OCP10_Patient;User Id=sa;Password=YourP@ssword123!"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - patientdb

  patientdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ocp10_patientdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourP@ssword123!"
