services:
  gateway:
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    container_name: ocp10_gateway
    ports:
      - "5000:5000"
    depends_on:
      - patientservice
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "5000"

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    container_name: ocp10_frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    volumes:
      - keys:/keys

  patientservice:
    image: ${DOCKER_REGISTRY-}patientservice
    container_name: ocp10_patientservice
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - patientdb

  patientdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ocp10_patientdb
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourP@ssword123!"

  noteservice:
    image: ${DOCKER_REGISTRY-}ocp10_noteservice
    container_name: ocp10_noteservice
    build:
      context: .
      dockerfile: NoteService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - notedb

  notedb:
    image: mongo:latest
    container_name: ocp10_notedb
    ports:
      - "27017:27017"
    volumes:
      - notedb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "YourPassword123"

volumes:
  mssql:
  notedb:
  keys: