services:
  gateway:
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    container_name: ocp10_gateway
    ports:
      - "5000:5000"
    depends_on:
      - patientservice
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "5000"

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    container_name: ocp10_frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile

  patientservice:
    image: ${DOCKER_REGISTRY-}patientservice
    container_name: ocp10_patientservice
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - patientdb

  patientdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ocp10_patientdb
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourP@ssword123!"

volumes:
  mssql: